---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
resources:
  - helmrelease-podinfo.yaml
configMapGenerator:
  - name: podinfo-helm-chart-values
    namespace: podinfo
    files:
      - values.yaml=podinfo-helm-chart-values.yaml
configurations:
  - kustomizeconfig.yaml
