---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../../common
  - helmrelease-podinfo.yaml
  - imageautomation-podinfo.yaml
configMapGenerator:
  - name: helm-chart-values-podinfo
    files:
      - values.yaml=helm-chart-values-podinfo.yaml
