---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common
  - helmrelease-podinfo.yaml
  - cert-wildcard-owoci.neggles.dev.yaml
configMapGenerator:
  - name: podinfo-helm-chart-values
    namespace: podinfo
    files:
      - values.yaml=podinfo-helm-chart-values.yaml
