apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: cert-manager
  valuesFrom:
    - kind: ConfigMap
      name: helm-chart-values-cert-manager
      valuesKey: values.yaml
