---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../common
  - helmrelease-cert-manager.yaml
  - sealedsecret-cloudflare-api-token-secret.yaml
configMapGenerator:
  - name: helm-chart-values-cert-manager
    files:
      - values.yaml=helm-chart-values-cert-manager.yaml
