---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
resources:
  - helmrelease-cert-manager.yaml
  - sealedsecret-cloudflare-api-token-secret.yaml
configMapGenerator:
  - name: cert-manager-helm-chart-values
    namespace: cert-manager
    files:
      - values.yaml=cert-manager-helm-chart-values.yaml
configurations:
  - kustomizeconfig.yaml
