---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - helmrelease-metallb.yaml
configMapGenerator:
  - name: helm-chart-values-metallb
    files:
      - values.yaml=helm-chart-values-metallb.yaml
configurations:
  - kustomizeconfig.yaml
