apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: topolvm
  namespace: topolvm-system
spec:
  releaseName: topolvm
  interval: 15m
  timeout: 5m

  chart:
    spec:
      chart: topolvm
      version: 11.0.x
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: helm-chart-values-topolvm
      valuesKey: values.yaml
