apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: topolvm
  namespace: topolvm-system
spec:
  chart:
    spec:
      chart: topolvm
      version: 3.x
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: topolvm
  valuesFrom:
    - kind: ConfigMap
      name: topolvm-helm-chart-values
      valuesKey: values.yaml
