---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: topolvm-system
resources:
  - ../../common
  - helmrelease-topolvm.yaml
configMapGenerator:
  - name: helm-chart-values-topolvm
    files:
      - values.yaml=helm-chart-values-topolvm.yaml
