---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common
  - helmrelease-topolvm.yaml
configMapGenerator:
  - name: topolvm-helm-chart-values
    namespace: topolvm-system
    files:
      - values.yaml=topolvm-helm-chart-values.yaml
