apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 20.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: traefik
  valuesFrom:
    - kind: ConfigMap
      name: helm-chart-values-traefik
      valuesKey: values.yaml
  values:
    ports:
      web:
        forwardedHeaders:
      websecure:
        forwardedHeaders:
