apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelist-cloudflare
spec:
  ipWhiteList:
    sourceRange:
      - 0.0.0.0/0
      - ::/0
    ipStrategy:
      excludedIPs:
        - 10.0.0.0/8 # RFC1918 class A
        - 172.16.0.0/12 # RFC1918 class Bs
        - 192.168.0.0/16 # RFC1918 class Cs
