apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: errors
spec:
  errors:
    status:
      - "500-599"
    query: /{status}.html
    service:
      name: whoami
      port: 80
