# Whitelisting Based on `X-Forwarded-For` with `depth=2`
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cf-whitelist
spec:
  ipWhiteList:
    sourceRange:
      - 0.0.0.0/0
    ipStrategy:
      # depth: 2
      excludedIPs:
        - 127.0.0.0/8
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - fc00::/7
        - "::1/128"
