apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: error-pages
spec:
  errors:
    status:
      - "400-401,403-405,407-413,416,418,429,500,502-505"
    query: /{status}.html
    service:
      name: error-pages
      port: 80
