apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: error-pages
spec:
  errors:
    status:
      - "400"
      - "401"
      - "403"
      - "404"
      - "405"
      - "407"
      - "408"
      - "413"
      - "416"
      - "418"
      - "429"
      - "500"
      - "502"
      - "503"
      - "504"
      - "505"
    query: /{status}.html
    service:
      kind: Service
      name: error-pages
      namespace: error-pages
      scheme: http
      port: http
