---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../common
  - helmrelease-traefik.yaml
  - http-middleware-ipwhitelist-admin.yaml
  - http-middleware-ipwhitelist-cloudflare.yaml
  # - http-middleware-errors.yaml
  - http-middleware-headers-hsts.yaml

components:
  - ../../components/ipwhitelist
  - ../../components/cloudflare

configMapGenerator:
  - name: helm-chart-values-traefik
    files:
      - values.yaml=helm-chart-values-traefik.yaml
