---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../common
  - helmrelease-traefik.yaml
  - http-middleware-cloudflarewarp.yaml
  - http-middleware-debug.yaml
  - http-middleware-default-chain.yaml
  - http-middleware-error-pages.yaml
  - http-middleware-headers-hsts.yaml
  - http-middleware-ipwhitelist-admin.yaml
  - http-middleware-ipwhitelist-cloudflare.yaml

configMapGenerator:
  - name: helm-chart-values-traefik
    files:
      - values.yaml=helm-chart-values-traefik.yaml

patches:
  # add cloudflare IPs to traefik header trust
  - path: patch-ports-trusted-ips.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: traefik

  # and to excluded IPs for ipwhitelist middleware
  - path: patch-ipwhitelist-excluded-ips.yaml
    target:
      group: traefik.containo.us
      version: v1alpha1
      kind: Middleware
      name: ipwhitelist-.*
