---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../common
  - helmrelease-traefik.yaml
  - http-middleware-error-pages.yaml
  - http-middleware-ipwhitelist-admin.yaml
  - http-middleware-ipwhitelist-cloudflare.yaml
  - http-middleware-headers-hsts.yaml
  - sealedsecret-traefik-hub-agent.yaml

configMapGenerator:
  - name: helm-chart-values-traefik
    files:
      - values.yaml=helm-chart-values-traefik.yaml
  - name: helm-chart-values-hub-agent
    files:
      - values.yaml=helm-chart-values-hub-agent.yaml

patches:
  # add cloudflare IPs to traefik header trust
  - path: patch-cloudflare-ips.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: traefik

  # add reserved IPs to IP whitelist middlewares
  - path: patch-reserved-ips.yaml
    target:
      group: traefik.containo.us
      version: v1alpha1
      kind: Middleware
      name: ipwhitelist-.*
