---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../common
  - helmrelease-traefik.yaml
  - http-middleware-ipwhitelist-admin.yaml
  - http-middleware-ipwhitelist-cloudflare.yaml
  # - http-middleware-errors.yaml
  - http-middleware-headers-hsts.yaml

configMapGenerator:
  - name: helm-chart-values-traefik
    files:
      - values.yaml=helm-chart-values-traefik.yaml

patches:
  - path: patch-ports-cloudflare-ips.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: traefik

  - path: patch-middleware-bogons.yaml
    target:
      group: traefik.containo.us
      version: v1alpha1
      kind: Middleware
      name: ipwhitelist-.*
