---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common
  - helmrelease-traefik.yaml
configMapGenerator:
  - name: traefik-helm-chart-values
    namespace: traefik
    files:
      - values.yaml=traefik-helm-chart-values.yaml
