---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../common
  - helmrelease-traefik.yaml
configMapGenerator:
  - name: helm-chart-values-traefik
    files:
      - values.yaml=helm-chart-values-traefik.yaml
