apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: reserved-ips.patch.yaml
    target:
      group: traefik.containo.us
      version: v1alpha1
      kind: Middleware
      name: ipwhitelist-.*
