apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hub-agent
  namespace: traefik
spec:
  releaseName: hub-agent
  interval: 15m
  timeout: 5m
  targetNamespace: traefik

  chart:
    spec:
      chart: hub-agent
      version: 1.2.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: helm-chart-values-hub-agent
      valuesKey: values.yaml
