apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-letsencrypt-cloudflare-parasocial.network-staging
  namespace: cert-letsencrypt-cloudflare
spec:
  secretName: cert-letsencrypt-cloudflare-parasocial.network-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "parasocial.network"
    - "*.parasocial.network"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
