apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-letsencrypt-cloudflare-parasocial.network
  namespace: cert-letsencrypt-cloudflare
spec:
  secretName: cert-wildcard-parasocial.network
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "parasocial.network"
    - "*.parasocial.network"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "traefik"
