---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common
  - helmrelease-elastic-operator.yaml
configMapGenerator:
  - name: helm-chart-values-eck-operator
    files:
      - values.yaml=helm-chart-values-eck-operator.yaml
