---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common
  - helmrelease-external-dns.yaml
configMapGenerator:
  - name: external-dns-helm-chart-values
    namespace: external-dns
    files:
      - values.yaml=external-dns-helm-chart-values.yaml
