---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - ../../common
  - helmrelease-external-dns.yaml

configMapGenerator:
  - name: helm-chart-values-external-dns
    files:
      - values.yaml=helm-chart-values-external-dns.yaml
