apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    cloudflare_api_token: AgDRmztuBlPkhZJpP12i/DDCum4K+uJWPWg359IaGMrIfoHc6M2+D+4Xvp9yUxUu5uyknZfMpxXt+gLs6Qvj8GVklnSgCEsfyoMCsdLKOMsi7xDDUMhzVly2n2a+dTG1C1RQL/z+nh2PCVrEYzyWh4VE7ouTK/h0YQe5rttCIhxN1a7MJ0uOLoHHLv75bxT1+OlN6GkHLAIZGzCPIaPcullfceX0FxnRQTLr+jKjOHT4/fhWcaL1qC7Q5u1OWdQ4KXoi3yqG7SvXFn/CHLeDSon3nAXKHrAPaANWtILR+bt/+SRmx+IPUY24Tq74RypckSwVdx3I+g5PefnPWX4mIG0QbcbMt6PFJz8L0gIDqoTHOh91t/pTior9qdJdwBrL5m/lsXGDWtr/0TnjYjDz6MxAPQvZweQkDaiUKHLUjaw2pw/dDCJPafq0eUcKQ8e5rEKKF+JSF6rAyYV/LNqquXaOBAhFTlbOog8QDHYfSO8q17YoQaS6HsfvoVwr2499rzPJBRMu0M2FFH1T+myBZLHF6IMQvmNmBLUzRg5icxNRwAIQGm9PVcUdj4VdmN8+iD303QYAFTe71gCslFjEFA6Isu6uCIczRMsfJIe7Z7AquxwbzAqKndXxkEwEs4UugIWrpswjJpjLNFGRBHec4/jm6AV7qc8TN7dDazvuHwcQZuKZ4e+pA5jFbSNeWhEGWjrB0rc6mGeJOjEILzUjAUJJgYVCLddhqjeIbqGwoYRyrm/D8ZmFZD3c
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: external-dns
    type: Opaque
