apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: config--metallb-system
  namespace: flux-system
spec:
  suspend: false # true will disable updates

  interval: 5m0s # detect drift and undo kubectl edits every 5m
  wait: true # wait for all applied resources to become ready
  timeout: 3m0s # give up waiting after three minutes
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: false # enable this to recreate resources on immutable fields changes

  path: ./metallb-config
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - name: metallb--metallb-system

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb-system
