---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
  namespace: mastodon
spec:
  chart:
    spec:
      chart: mastodon
      version: 4.x
      sourceRef:
        kind: GitRepository
        name: mastodon
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: mastodon
  valuesFrom:
    - kind: ConfigMap
      name: mastodon-helm-chart-values
      valuesKey: values.yaml
