---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
  namespace: mastodon
spec:
  releaseName: mastodon
  interval: 10m
  timeout: 5m

  chart:
    spec:
      chart: .
      version: 4.x
      sourceRef:
        kind: GitRepository
        name: mastodon
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: helm-chart-values-mastodon
      valuesKey: values.yaml
