---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
  namespace: mastodon
spec:
  releaseName: mastodon
  interval: 15m
  timeout: 5m

  chart:
    spec:
      chart: mastodon
      version: 4.x
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: neggles
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: helm-chart-values-mastodon
      valuesKey: values.yaml
