apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mastodon-postgres-password
  namespace: mastodon
spec:
  encryptedData:
    password: AgAmLoJWpmgwdWkBhAbBOptCQYTd3ZKy55bkTqZmWyCHs9m0U7S7W95Bpq9/7mBl/j9kIbU+8W6Y4IeguOyR6Dymak25MIjyEMH4ASlRC3RdQPOt1YfKHgusXrdgBe60mtDjZUAVwBplmSNuIZyc4WKa2yo0/ARheCRGVQ5vbZ72iuGiuCUAMg/9kC4ybZTSSO79kh2q6lXLAVPWiBpaF1E2tSi0EKNQvoB5QvOSvl5u8WURpQApLJQJhJsLJ+ko5o/YRXpaP/FXqlEHh92xEjpKEkQpb+zD3tItSNR2m+fedNqa5z7PuD/BDxbIN/kJhLHGxI9HO7YK6Ef3bd5OezvkpuOVYP3ilM+N4BV+TtVXO4LfezWD0CGLgI35kEmyJlM5gdrFEVS/NHaNeXrJZNK7Q3e/GEOKWR/k00oYHuW0xsaxENAWdhf+Jy3e+O0zmHnDXkUqxh8o1IJrzMk4t+GSXHNZ8htOWlnMjL7C4uAE+bljerr17bCllVXgGkVYYMGykHYPd0WTF2uVbmlUXdcu7ktSbiSLnqyATS04DnGdYcURsLTQdwkz+54NPvE57gGM+r2ZKOgzJuZj/5WeCZvVRx/Kj6PKbPzXxnZQi2TvwhJYaF+ldnkp3mngzpy3x5GJI1ewVyTMZlNKIiP58tDILfV/Td/Gor2VN01mCGfphKshMbBeQQhhCE6RPQl7rcR04BmkYUSn8cRG8ju0BRncrVavz+OPih9fiMj9fcsMZWDcL2haIWAy31O5c2Npufup4uWMZBfKtGW+/6CA83k8
    postgres-password: AgAfvD2q5USyCbJd03LoquAUdTkNoJelnJY5dncSIEqf+53jItsy9uxUtvRZ6t5UrqJLIpZ/UWc9XKbmepOVhbA8TYv9Y9B/LHtP0+wwKvXjFITArGLjIR4GXU5fSvFbSgINjdbkJfTJjbIjkAi26YPgJQibXgdap0btGI9LU8iYzUWKB9FkyjaIsFSjyLAIxRylwj4as5+Tg1zV2aw8iNTM6Jyu7jfUA935/Pt24D3lbyfvvMYljezkVGIGA8T1WoYXBW9CtUchvQOyAPKHGBYxIF3HQZh8HsidzmU3IhV7QZg89+p+ifnScyslTyB/MlPILOBt4OwMGhA9REj/ifuUjwEBs1XSbVlh1j7q6sdQidUi5276e4RdoRrQKpwJxXZ0fEDbe62Ezj198gFU0jPP2KQ7XsWZltKYz0naSDlG0gxHtlK+7woY1lv82dUrF0e0bcLsrr5dikjw9gg5E/XhPw1w1CeYLHMqq+LUvG1DRcLfo2uxHYasR/DTY/ITjmJi6bshLoHOoqJNqaEH63E7VISgEAuNNccmaXnnd7SvVWcYrjLifX9Dmh3h4LEyqVklbI8RHtqMSUTdNPB3ixUBE8T6FSHiUpf121oTYrGwUwa04KjhcWdJt1HY23H6L9wgHdpQN2uYWJNiJsptmbi++Ea4T+XKsoc8paDBL//y1vlPa5ThqH2qed3SKxBNA8xkMVicgxS+EwrYi0dn42HB31nmujfPKRQkCywvrh0iffeKIfRrpbVH3fev41SqGjLX5bK4xx6W0PB+00DP5kyd
  template:
    metadata:
      creationTimestamp: null
      name: mastodon-postgres-password
      namespace: mastodon
    type: Opaque

