apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mastodon-postgres-password
  namespace: mastodon
spec:
  encryptedData:
    postgres-password: AgCQ6AIvCvkq0G4a7Lsmb0nSwTvp5ppWaMMy6SaEtACdseIdHgK/p9OoB8uzcap4gtTvytIt6jAusJbDD2ljGF3mrapqT+U21dDaMcSdPpohY9sC6jfTMD6klX+68dQCyh+2nkQLQrovQ+de+BxR+iM2AAfK4V7qst9P2vTi8U9H4QOwzqRrKd92UffMdpy9DPwTC/IDYdWOjjM+uvHu+Okx3dee6EC1LlhZ9T8LnP39l1PuUCneL2tY+5pHTH5TQl5waOtkzKI5p2IZMIE+9EgML58P8tlcOzWqaJi9jJKJ60KFN2SKrmFGpWVl+5jyr0eEP491b/ewcbocU/R5gBlDlk1nAINlfvuuGzly16MacLlQQvLwt/eoJuyLokFCJ3PvPdlYhNkQjp+x+zRDgNnM+7cJc8l2QHQGZwd7pfMZQBJYNzunxqdguQg+pdFGLZ9yM56vFPUEsJo1MQVve1jqMhpg7e9vUjaT2foF0MyEBNXZZyCXrGjXyF5zZMMI2Crmq4qfU84ZwK5Bh9hmCMYaGu2s4/6P+LIi1TKuRIulKtCRRpW0eVXvXxrvTOVzN2/DiFEIXfinalYdKCWl5oEtc40p3Cc9PcyCgU7Em7a3Rp0RpKVRpWHsGtws0eFWuOtd4QUf6ppAB8hbu61IKN5SgC1o31fPEVILNeMwyRD1PvlZrtTm9qRajRn9pwmf7nk7fTCpBOM6LE1rVkNoiga8O59QmCaZdEB/ck68fMM3FcjSxgj65D1XBGaVV89Av05xKCAYdKc09zQCLILK1dk9
  template:
    metadata:
      creationTimestamp: null
      name: mastodon-postgres-password
      namespace: mastodon
    type: Opaque
