apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mastodon-sendgrid-api-key
  namespace: mastodon
spec:
  encryptedData:
    login: AgCKwttQZ+U8V9nU/twJ/yvyyDq40N4T/gjIzVfNbOmggDiGwmAYCAgI68El4E4QoLylIiQ/iU1n9iuqLaL3HPfNbQXZnrDLUwqzBHuC1Kr8Eb4arCkWNIXdGNW+KckeYOezXi5UGUROOW2Q2K5E7q9aqGYfgtUdSRJ9TsGo3iRdQIviZGvTFizgbrlmPWWP8vNJJW16hy+yWDCae+a/Ju2gc3W+50dzHnR87eRHoVW2CYx7PWEjFjZotPvk6kpUyVgAh+S5y0v9SuTBprn8AoyIPwyB+EcvuTzH7Ik1L2CBasA7+f9F2pxm5kljmS+X4cTRb6fHfdfo1l/GXDtw2xc4V9Tx3cLJPaZfUvw23paVtkN02U2z+oKug4u1tb5YS3jgQ3w4ShcB4LslSrEAWp/7MJk3x9lymnJYPO5ohVpQYHfkVywUgTf1NBBFVdILbOVEWUZCKiKGrisy7M1k0TldFPnbodANMhJ2SAL6vqqhQ5WsZxgxgogvVW3UPCpAMpU6yr/Vxp/BuYdIt4eNnY5Pesx8G3uW0j42CX2qBQc1C8odQR0exCO4JPN3wbzVzA36BV4Y0rr4x5gBT9fbyQwamTeZLDXgDTthQ5u2KspxJ+xa9TYR5rs1+jwqDh7cKtaDmzbJdkgYsl0jJf2uH7QaC4wJIcb22+5k0yCveqVXYkBkmlMUQRw7FNvEL16DVWSxGQGbx3A=
    password: AgB1MuNT1oKnj0uifxP2ycc/fVpojb1ca2S9oG/5tvvZjJsJOeyCZZlSzE6djpb9BahLfLdxKksnt0bReCVwngcoIY6nJUCzmjK2LYCCgzlLr39/ESKoAmVi/G+onMYDy85ijBLdjYY5l/kPCcnweKGdtD4LahNgtwKzpmaBQmXjHq51ICzukWGMI2sZtt6v2gjnCh1xivjIcX2Sag7oDnzgZuUeLywJ7cxmdCzglih08QvgP7dRl+uyoXkKdi5MC5ayjGARFHR1FoZtj2nfoY6+MPhXKRtPTBLCVlYRwAVjwMc0rsvzUpdQzqhyPBtJno1Dx6U75aV8abmXdRAME7m9oqqLsqv+g1iT5Sg2HdhAbjZjxzGG0QG2Y28/1p5qw/WkWJ/tU4+/mjOHu2jTeffzwV8fFMnxQHZzE++1fSG2P1eH0G+6eLMlCaeCmVTq2px2UsDr6rWv2mfD1FpHbVFZ3ppHH4FLP/CKJDmR6waszKSl4URCiqVkvTV1v9mx5QtaVz7inTDfiVx9WvAzIM3R8HsIZg2hFYER+MbVu1rPwc1zakIZChUdeFax5jEbCOTIgwKdJZK4DW5CZxuo/lsaDu7rpXs84nYaKBIQNc7NSSY7zLwsSmo/NEbjEQq/pzoRONBuXSAuqZLH3JqW93DXWQxJWG6iaJxCn0s4ZobzmKsMHGCf4DHCgITEggiqizWlxOIOh8cPpDZeCfO4Vi8nH2eDp7RweRbCdVWwNtwHflpim8Zj7gSb6VaFj/91Sebe8E2r2jcroVUfup71pAeZSqO31Oo=
  template:
    metadata:
      creationTimestamp: null
      name: mastodon-sendgrid-api-key
      namespace: mastodon
    type: Opaque
