---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common
  - helmrelease-sealed-secrets.yaml
configMapGenerator:
  - name: helm-chart-values-sealed-secrets
    namespace: sealed-secrets
    files:
      - values.yaml=helm-chart-values-sealed-secrets.yaml
