---
# Bind the cluster admin role to the wego-admin group
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-admin-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: wego-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wego-admin-cluster-role
---
# Bind the cluster admin role to the AAD gitops admin group
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-admin-aad
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: aad:45869dc4-65ae-41ed-961d-83c6159da5ec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wego-admin-cluster-role

---
# Bind the read-only role to the read-only group
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-readonly-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: wego-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wego-readonly-role
---
# Bind the read-only role to the AAD read-only group
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-readonly-aad
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: aad:7404b830-03f6-4eaf-b20c-e12fbe49c176
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wego-readonly-role
