apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  releaseName: reflector
  interval: 15m
  timeout: 5m

  chart:
    spec:
      chart: reflector
      version: 6.1.x
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: helm-chart-values-reflector
      valuesKey: values.yaml
