apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reflector
resources:
  - ../../common
  - helmrelease-reflector.yaml

configMapGenerator:
  - name: helm-chart-values-reflector
    files:
      - values.yaml=helm-chart-values-reflector.yaml
