---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common
  - helmrelease-reflector.yaml
configMapGenerator:
  - name: reflector-helm-chart-values
    namespace: reflector
    files:
      - values.yaml=reflector-helm-chart-values.yaml
