---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: error-pages
  namespace: error-pages
spec:
  releaseName: error-pages
  interval: 10m
  timeout: 5m

  chart:
    spec:
      chart: error-pages
      version: 0.x.x
      sourceRef:
        kind: HelmRepository
        name: neggles
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: helm-chart-values-error-pages
      valuesKey: values.yaml
