---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: error-pages
resources:
  - ../../common
  - helmrelease-error-pages.yaml
configMapGenerator:
  - name: helm-chart-values-error-pages
    files:
      - values.yaml=helm-chart-values-error-pages.yaml
