name: Image Automation PR
run-name: AutoPR for ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.ref_name }}
on:
  push:
    branches:
      - "auto/**"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to open PR from"
        required: true
        type: string

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}-auto
  cancel-in-progress: false

env:
  PR_REF_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.ref_name }}

jobs:
  open:
    name: Create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ env.PR_REF_NAME }}

      - name: Create PR
        id: create-pr
        run: |
          PR_REF_NAME="${PR_REF_NAME##*/}"
          gh pr create --fill --title "Auto-update for $PR_REF_NAME"
