name: Image Automation PR
run-name: AutoPR for ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.ref_name }}
on:
  push:
    branches:
      - "auto/**"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to open PR from"
        required: true
        type: string

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}-auto
  cancel-in-progress: false

env:
  PR_REF_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.branch || github.ref_name }}

jobs:
  open:
    name: Create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create PR
        id: create-pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          APP_NAME=$(echo ${PR_REF_NAME} | cut -f2- -d'/');
          function gh_pr() { (gh pr create --fill --title "$1") || (gh pr edit --fill --title "$1") };
          gh_pr "Auto-update for $PR_REF_NAME"
